# -*- coding: utf-8 -*-
"""real_est

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vznq56S0IDJb4nyWW9WP8VcJlDHMz7fD
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup

url="https://www.buyrentkenya.com/property-for-rent"

data=requests.get(url)
data.status_code

soup=BeautifulSoup(data.text, "lxml")

import requests
from bs4 import BeautifulSoup

base_url = "https://www.buyrentkenya.com/property-for-rent?page="
total_pages = 394
all_prices = []

for page_number in range(1, total_pages + 1):
    url = base_url + str(page_number)
    data = requests.get(url)
    soup = BeautifulSoup(data.text, "lxml")

    prices = [price.text.strip().replace('\n', '') for price in soup.find_all("div", attrs={"data-cy": "card-price", "class": "hidden md:flex justify-between"})]
    filtered_prices = [price for price in prices if price.startswith('KSh')]
    all_prices.extend(filtered_prices)

for price in all_prices:
    print(price)

import requests
from bs4 import BeautifulSoup

base_url = "https://www.buyrentkenya.com/property-for-rent?page="
total_pages = 394
listings = []

for page_number in range(1, total_pages + 1):
    url = base_url + str(page_number)
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "lxml")

    bedrooms = soup.find_all("span", attrs={"data-cy": "card-beds", "class": "whitespace-nowrap font-normal"})
    bathrooms = soup.find_all("span", attrs={"class": "whitespace-nowrap font-normal", "data-cy": "card-baths"})
    locations = soup.find_all("p", class_="text-sm font-normal text-grey-650 truncate ml-1")
    prices = soup.find_all("div", attrs={"data-cy": "card-price", "class": "hidden md:flex justify-between"})
    titles = soup.find_all("span", class_="hidden md:inline")

    for bedroom, bathroom, location, price, title in zip(bedrooms, bathrooms, locations, prices, titles):
        bedroom_count = bedroom.text.strip()
        bathroom_count = bathroom.text.strip()
        location_name = location.text.strip()
        price_value = price.text.strip().replace('KSh', '').replace(',', '').strip()
        title_name = title.text.strip()

        listing = {
            "location": location_name,
            "price": price_value,
            "bedrooms": bedroom_count,
            "bathrooms": bathroom_count,
            "title": title_name
        }
        listings.append(listing)

# Print the list of listings
for listing in listings:
    print(listing)

df=pd.DataFrame(listings)
df.head(10)



df = df[['title', 'location', 'bathrooms', 'bedrooms', 'price']]
df.head(10)

# Below is just specific code of the above code

"""# New Section"""

location=soup.find_all("p", class_ = "text-sm font-normal text-grey-650 truncate ml-1")
# location

bedrooms = soup.find_all("span", attrs={"data-cy": "card-beds", "class": "whitespace-nowrap font-normal"})
# bedrooms

bathrooms=soup.find_all("span", attrs={"class":"whitespace-nowrap font-normal","data-cy":"card-baths"})
# bathrooms

prices=[price.text for price in soup.find_all("div", attrs={"data-cy": "card-price", "class": "hidden md:flex justify-between"})]
# prices

prices = [price.strip().replace('\n', '') for price in prices]
filtered_prices = [price for price in prices if price.startswith('KSh')]

# print(filtered_prices)